### ISSUE TITLE
HUH! Found abab-1.0.3.tgz more than once!

### ISSUE THREAD

**Issue by alicebob** [moretea/yarn2nix#30]
running yarn2nix gives me:

```
yarn2nix > yarn.nix
HUH! Found abab-1.0.3.tgz more than once!
Ignoring second declaration..
HUH! Found accepts-1.3.3.tgz more than once!
Ignoring second declaration..
```
(And so on for a while).

The relevant looking part from yarn.lock:

```
abab@^1.0.0, abab@^1.0.3:
  version "1.0.3"
  resolved "https://registry.yarnpkg.com/abab/-/abab-1.0.3.tgz#b81de5f7274ec4e756d797cd834f303642724e5d"

abbrev@1:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/abbrev/-/abbrev-1.1.0.tgz#d0554c2256636e2f56e7c2e5ad183f859428d81f"

accepts@1.3.3, accepts@~1.3.3:
  version "1.3.3"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.3.tgz#c3ca7434938648c3e0d9c1e328dd68b622c284ca"
  dependencies:
    mime-types "~2.1.11"
    negotiator "0.6.1"
```

Seems like the entries with multiple values generate a warning. Since this is as it's generated by yarn maybe yarn2nix could deal with this without warnings?

Thanks!

**Comment by moretea** [comment]
This message is generated here https://github.com/moretea/yarn2nix/blob/master/bin/yarn2nix.js#L26

As you can see in your output,  it prints out the actual _locked_ version. The warning was used during debugging and should just be removed.

**Comment by moretea** [comment]
Removed in https://github.com/moretea/yarn2nix/pull/34
