### ISSUE TITLE
node_modules in $out/libexec/packagename/node_modules

### ISSUE THREAD

**Issue by offlinehacker** [moretea/yarn2nix#4]
`node_modules` should be placed in `$out/libexec/packagename/node_modules` and then wrappers to bin folder should be created (using makeWrapper or symlinks)

**Comment by moretea** [comment]
Ok, why exactly? I'm quite clueless when it comes to javascript.

**Comment by offlinehacker** [comment]
When we will have yarn packages in nixpkgs, if you will install yarn
package, you really want it to link files to standard fhs paths, and don't
want to polute with non standard paths like node_modules

**Comment by moretea** [comment]
Given that it's prefixed by an `$out`, I'm not too worried about that. There are many derivations that output a single file even, right?
