### ISSUE TITLE
attribute yarn from documentation missing

### ISSUE THREAD

**Issue by qknight** [moretea/yarn2nix#43]
the README.md states:
```
cd $GIT_REPO
nix-env -i yarn2nix -f .
nix-env -i yarn -f .
```

but there is no yarn attribute in default.nix so it fails....

**Comment by zimbatm** [comment]
yarn is now taken directly from nixpkgs so you can `nix-env -i yarn` without the `-f .` bit. nonetheless #44 should fix the installation instructions.

**Comment by qknight** [comment]
cool!
