### ISSUE TITLE
Integrate buildYarnPackage into nixpkgs

### ISSUE THREAD

**Issue by offlinehacker** [moretea/yarn2nix#5]
This function should be part of nixpkgs, so we can start adding yarn packages

**Comment by moretea** [comment]
Agreed! I'm working with @zimbatm and @manveru on getting a v1 ready.

Then we'll have to see if/how we can split this project in a `yarn2nix` project, and a `buildYarnPackage` function that can be inlined in nixpkgs.

**Comment by manveru** [comment]
I've started work on this here: https://github.com/NixOS/nixpkgs/pull/35340

**Comment by frontsideair** [comment]
I think this can be closed. 😃

**Comment by zimbatm** [comment]
Right, it's integrated but messy. nixpkgs can't use it because of IFD restrictions in hydra
